- id: gen-readme
  name: Check readme contents
  entry: gen-readme
  language: python
  require_serial: true
  # args:
  #   - "--org-name"
  #   - "--repo-name"
  #   - "--branch"
  #   - "--gen-html"
