- id: gen-readme
  name: check readme contents
  entry: gen-readme
  language: python
  require_serial: true
  args:
    - "--min-description-words"
    - "--website"
    - "--org-name"
    - "--author"
